### ISSUE TITLE
Coloring script failure on zero-error edge case.

### ISSUE THREAD

**Issue by gtisdelle** [lam2mo/shval#8]
## Behavior
Coloring script crashes when program has little error.

## Expected Behavior
The script should still show the operations even if there is no error.

## Steps to reproduce
1. Run the pintool on the arith test program
2. run `color_diff.rb trace.dot > color.dot`

## Trigger conditions
Little floating point error in the program

## Symptoms
No nodes in the resulting color graph

**Comment by gtisdelle** [comment]
Hi! I'm currently looking into this. I wanted to clarify the issue, so I updated the post.

I'm thinking that this behavior may be intentional. It looks like the clusters are collapsed when the relative error is 0.

**Comment by lam2mo** [comment]
Oh hey @gtisdelle, glad you're looking into this again and thanks for writing down the additional info. Unfortunately given the situation I'm unlikely to have any spare cycles to work on SHVAL this summer but I'm happy to check in occasionally and offer some consultation if you're interested in continuing to work on it yourself. Feel free to use my Calendly (link on my faculty website) if you want to have a Zoom meeting.

If the issue is as you describe, it seems to me that there should be a flag that is off by default that suppresses zero-error nodes. I can't remember if anyone ever implemented that.

**Comment by gtisdelle** [comment]
Thanks, I completely understand.

I'm actually having some trouble getting the diff tool to output function names into the graphviz `trace.dot` file. If I remember correctly, all I needed to do was compile with the `-g` option to get the debugging symbols. Is that correct?

**Comment by gtisdelle** [comment]
Never mind about that question.

I was running
``
pin -t /path/to/tool -- ./program
``

Instead of
``
pin -t /path/to/tool -T -- ./program
``
